soundfont = "/usr/share/sounds/sf2/default-GM.sf2"

[[instr."Staff_violinI:"]]
preset = 40
pan = -0.5

[[instr."Staff_violinI:"]]
preset = 40
pan = -0.7

[[instr."Staff_violinII:"]]
preset = 40
pan = -0.4

[[instr."Staff_violinII:"]]
preset = 40
pan = -0.3

[[instr."Staff_viola:"]]
preset = 41
pan = -0.5

[[instr."Staff_continuo:"]]
preset = 42
pan = 0.4

[[instr."Staff_continuo:"]]
preset = 42
pan = 0.6

[[instr."Staff_continuo:"]]
preset = 43
pan = 0.7
tsp = -12
gain = 3

[[instr."upper:"]]
preset = 6
pan = 0.3

[[instr."lower:"]]
preset = 6
pan = 0.3
